import java.net.URL;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.Mixer;
//
import java.io.IOException;
import java.io.ObjectOutputStream;

import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author godie
 */

public class Consol extends javax.swing.JFrame {

    /**
     * Creates new form Consol
     */
    public static Mixer mixer;
    public static Clip clip1;
    public static Clip clip2;
    public static Clip clip3;
    public static Clip clip4;
    Secuenciador sc = new Secuenciador();

    public Consol() {
        initComponents();
        Mixer.Info[] mixInfos = AudioSystem.getMixerInfo();
        mixer = AudioSystem.getMixer(mixInfos[0]);
    
        DataLine.Info dataInfo = new DataLine.Info(Clip.class,null);

        try{
            clip1 = (Clip)mixer.getLine(dataInfo);
            clip2 = (Clip)mixer.getLine(dataInfo);
            clip3 = (Clip)mixer.getLine(dataInfo);
            clip4 = (Clip)mixer.getLine(dataInfo);
        }catch(Exception e){

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JToggleButton();
        b2 = new javax.swing.JToggleButton();
        b3 = new javax.swing.JToggleButton();
        b4 = new javax.swing.JToggleButton();
        b5 = new javax.swing.JToggleButton();
        b6 = new javax.swing.JToggleButton();
        b7 = new javax.swing.JToggleButton();
        b8 = new javax.swing.JToggleButton();
        b9 = new javax.swing.JToggleButton();
        b10 = new javax.swing.JToggleButton();
        b11 = new javax.swing.JToggleButton();
        b12 = new javax.swing.JToggleButton();
        b13 = new javax.swing.JToggleButton();
        b14 = new javax.swing.JToggleButton();
        b15 = new javax.swing.JToggleButton();
        b16 = new javax.swing.JToggleButton();
        b17 = new javax.swing.JToggleButton();
        b18 = new javax.swing.JToggleButton();
        b19 = new javax.swing.JToggleButton();
        b20 = new javax.swing.JToggleButton();
        b21 = new javax.swing.JToggleButton();
        b22 = new javax.swing.JToggleButton();
        b23 = new javax.swing.JToggleButton();
        b24 = new javax.swing.JToggleButton();
        b25 = new javax.swing.JToggleButton();
        b26 = new javax.swing.JToggleButton();
        b27 = new javax.swing.JToggleButton();
        b28 = new javax.swing.JToggleButton();
        b29 = new javax.swing.JToggleButton();
        b30 = new javax.swing.JToggleButton();
        b31 = new javax.swing.JToggleButton();
        b32 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        textSpeed = new javax.swing.JTextField();
        textRepeat = new javax.swing.JTextField();
        btnPlay = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(151, 36, 208));

        b1.setBackground(new java.awt.Color(1, 1, 1));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(1, 1, 1));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(1, 1, 1));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(1, 1, 1));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(1, 1, 1));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(1, 1, 1));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(1, 1, 1));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(1, 1, 1));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(1, 1, 1));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b10.setBackground(new java.awt.Color(1, 1, 1));
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        b11.setBackground(new java.awt.Color(1, 1, 1));
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b12.setBackground(new java.awt.Color(1, 1, 1));
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b13.setBackground(new java.awt.Color(1, 1, 1));
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b14.setBackground(new java.awt.Color(1, 1, 1));
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b15.setBackground(new java.awt.Color(1, 1, 1));
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b16.setBackground(new java.awt.Color(1, 1, 1));
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });

        b17.setBackground(new java.awt.Color(1, 1, 1));
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });

        b18.setBackground(new java.awt.Color(1, 1, 1));
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });

        b19.setBackground(new java.awt.Color(1, 1, 1));
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });

        b20.setBackground(new java.awt.Color(1, 1, 1));
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });

        b21.setBackground(new java.awt.Color(1, 1, 1));
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });

        b22.setBackground(new java.awt.Color(1, 1, 1));
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });

        b23.setBackground(new java.awt.Color(1, 1, 1));
        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });

        b24.setBackground(new java.awt.Color(1, 1, 1));
        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });

        b25.setBackground(new java.awt.Color(1, 1, 1));
        b25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b25ActionPerformed(evt);
            }
        });

        b26.setBackground(new java.awt.Color(1, 1, 1));
        b26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b26ActionPerformed(evt);
            }
        });

        b27.setBackground(new java.awt.Color(1, 1, 1));
        b27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b27ActionPerformed(evt);
            }
        });

        b28.setBackground(new java.awt.Color(1, 1, 1));
        b28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b28ActionPerformed(evt);
            }
        });

        b29.setBackground(new java.awt.Color(1, 1, 1));
        b29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b29ActionPerformed(evt);
            }
        });

        b30.setBackground(new java.awt.Color(1, 1, 1));
        b30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b30ActionPerformed(evt);
            }
        });

        b31.setBackground(new java.awt.Color(1, 1, 1));
        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31ActionPerformed(evt);
            }
        });

        b32.setBackground(new java.awt.Color(1, 1, 1));
        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(237, 144, 74));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setText("TAROLA ;D");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(28, 28, 28))
        );

        jPanel3.setBackground(new java.awt.Color(237, 144, 74));

        jLabel7.setText("PERCUSIÓN OwO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(237, 144, 74));

        jLabel8.setText("BOMBO :P");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(237, 144, 74));

        jLabel9.setText("Hi-Hats :V");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(49, 49, 49))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(151, 36, 208));

        textSpeed.setText("Especifica aquí la velocidad (bpm)");
        textSpeed.setToolTipText("");
        textSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSpeedActionPerformed(evt);
            }
        });

        textRepeat.setText("Especifica el número de repeticiones");
        textRepeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRepeatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textSpeed)
                    .addComponent(textRepeat))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(textSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnPlay.setBackground(new java.awt.Color(0, 153, 102));
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-reproducir-en-círculo-30.png"))); // NOI18N
        btnPlay.setPreferredSize(new java.awt.Dimension(50, 50));
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnStop.setBackground(new java.awt.Color(153, 0, 0));
        btnStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-detener-en-círculos-30.png"))); // NOI18N
        btnStop.setPreferredSize(new java.awt.Dimension(50, 50));
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-bass-drum-50.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-snare-drum-top-50.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-drum-set-50.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cymbals-50.png"))); // NOI18N

        jLabel10.setBackground(new java.awt.Color(224, 143, 61));
        jLabel10.setForeground(new java.awt.Color(224, 143, 61));
        jLabel10.setText("Secuenciador de Amairany y Diego :3 ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel5)
                        .addGap(213, 213, 213)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b24, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b25, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b26, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b27, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b28, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b29, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b30, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b31, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b32, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b29, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b30, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b31, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b32, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(b25, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b26, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b27, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b28, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b23, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b24, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(b17, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b18, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b19, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32ActionPerformed
        // TODO add your handling code here:
        if(b32.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4hi_hat.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(7, true);
            System.out.println("Arreglo:" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        }else{
            sc.lin4.set(7,false);
            System.out.println("Arreglo:" + sc.lin4.toString());
        }
    }//GEN-LAST:event_b32ActionPerformed

    private void b31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31ActionPerformed
        // TODO add your handling code here:
        if(b31.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3bombo.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(7, true);
            System.out.println("Arreglo:" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        }else{
            sc.lin3.set(7,false);
            System.out.println("Arreglo:" + sc.lin3.toString());
        }
    }//GEN-LAST:event_b31ActionPerformed

    private void b30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b30ActionPerformed
        // TODO add your handling code here:
        if(b30.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2percusion.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(7, true);
            System.out.println("Arreglo:" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        }else{
            sc.lin2.set(7,false);
            System.out.println("Arreglo:" + sc.lin2.toString());
        }
    }//GEN-LAST:event_b30ActionPerformed

    private void b29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b29ActionPerformed
        // TODO add your handling code here:
        if(b29.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1tarola.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(7, true);
            System.out.println("Arreglo:" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        }else{
            sc.lin1.set(7,false);
            System.out.println("Arreglo:" + sc.lin1.toString());
        }
    }//GEN-LAST:event_b29ActionPerformed

    private void b28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b28ActionPerformed
        // TODO add your handling code here:
        if(b28.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4hi_hat.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(6, true);
            System.out.println("Arreglo:" + sc.lin4.toString());
            clip4.open(audioStream); 
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        }else{
            sc.lin4.set(6,false);
            System.out.println("Arreglo:" + sc.lin4.toString());
        }
    }//GEN-LAST:event_b28ActionPerformed

    private void b27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b27ActionPerformed
        // TODO add your handling code here:
        if(b27.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3bombo.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(6, true);
            System.out.println("Arreglo:" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        }else{
            sc.lin3.set(6,false);
            System.out.println("Arreglo:" + sc.lin3.toString());
        }
    }//GEN-LAST:event_b27ActionPerformed

    private void b26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b26ActionPerformed
        // TODO add your handling code here:
        if(b26.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2percusion.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(6, true);
            System.out.println("Arreglo:" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        
        }else{
            sc.lin2.set(6,false);
            System.out.println("Arreglo:" + sc.lin2.toString());
        }
    }//GEN-LAST:event_b26ActionPerformed

    private void b25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b25ActionPerformed
        // TODO add your handling code here:
        if(b25.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1tarola.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(6, true);
            System.out.println("Arreglo:" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        }else{
            sc.lin1.set(6,false);
            System.out.println("Arreglo:" + sc.lin1.toString());
        }
    }//GEN-LAST:event_b25ActionPerformed

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
        // TODO add your handling code here:
        if(b24.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4hi_hat.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(5, true);
            System.out.println("Arreglo:" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        }else{
            sc.lin4.set(5,false);
            System.out.println("Arreglo:" + sc.lin4.toString());
        }
    }//GEN-LAST:event_b24ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
        // TODO add your handling code here:
        if(b23.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3bombo.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(5, true);
            System.out.println("Arreglo:" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        }else{
            sc.lin3.set(5,false);
            System.out.println("Arreglo:" + sc.lin3.toString());
        }
    }//GEN-LAST:event_b23ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
        // TODO add your handling code here:
        if(b22.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2percusion.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(5, true);
            System.out.println("Arreglo:" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        }else{
            sc.lin2.set(5,false);
            System.out.println("Arreglo:" + sc.lin2.toString());
        }
    }//GEN-LAST:event_b22ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
        // TODO add your handling code here:
        if(b21.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1tarola.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(5, true);
            System.out.println("Arreglo:" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        }else{
            sc.lin1.set(5,false);
            System.out.println("Arreglo:" + sc.lin1.toString());
        }
    }//GEN-LAST:event_b21ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
        // TODO add your handling code here:
        if(b20.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4hi_hat.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(4, true);
            System.out.println("Arreglo:" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        }else{
            sc.lin4.set(4,false);
            System.out.println("Arreglo:" + sc.lin4.toString());
        }
    }//GEN-LAST:event_b20ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
        // TODO add your handling code here:
        if(b19.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3bombo.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(4, true);
            System.out.println("Arreglo:" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        }else{
            sc.lin3.set(4,false);
            System.out.println("Arreglo:" + sc.lin3.toString());
        }
    }//GEN-LAST:event_b19ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
        // TODO add your handling code here:
        if(b18.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2percusion.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(4, true);
            System.out.println("Arreglo:" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        }else{
            sc.lin2.set(4,false);
            System.out.println("Arreglo:" + sc.lin2.toString());
        }
    }//GEN-LAST:event_b18ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
        // TODO add your handling code here:
        if(b17.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1tarola.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(4, true);
            System.out.println("Arreglo:" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        }else{
            sc.lin1.set(4,false);
            System.out.println("Arreglo:" + sc.lin1.toString());
        }
    }//GEN-LAST:event_b17ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        // TODO add your handling code here:
        if(b16.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4hi_hat.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(3, true);
            System.out.println("Arreglo:" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        }else{
            sc.lin4.set(3,false);
            System.out.println("Arreglo:" + sc.lin4.toString());
        }
    }//GEN-LAST:event_b16ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        // TODO add your handling code here:
        if(b15.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3bombo.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(3, true);
            System.out.println("Arreglo:" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        }else{
            sc.lin3.set(3,false);
            System.out.println("Arreglo:" + sc.lin3.toString());
        }
    }//GEN-LAST:event_b15ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        // TODO add your handling code here:
        if(b14.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2percusion.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(3, true);
            System.out.println("Arreglo:" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        }else{
            sc.lin2.set(3,false);
            System.out.println("Arreglo:" + sc.lin2.toString());
        }
    }//GEN-LAST:event_b14ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        // TODO add your handling code here:
        if(b13.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1tarola.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(3, true);
            System.out.println("Arreglo:" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        }else{
            sc.lin1.set(3,false);
            System.out.println("Arreglo:" + sc.lin1.toString());
        }
    }//GEN-LAST:event_b13ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
        if(b12.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4hi_hat.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(2, true);
            System.out.println("Arreglo:" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        }else{
            sc.lin4.set(2,false);
            System.out.println("Arreglo:" + sc.lin4.toString());
        }
    }//GEN-LAST:event_b12ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        if(b11.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3bombo.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(2, true);
            System.out.println("Arreglo:" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        }else{
            sc.lin3.set(2,false);
            System.out.println("Arreglo:" + sc.lin3.toString());
        }
    }//GEN-LAST:event_b11ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        if(b10.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2percusion.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(2, true);
            System.out.println("Arreglo:" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        }else{
            sc.lin2.set(2,false);
            System.out.println("Arreglo:" + sc.lin2.toString());
        }
    }//GEN-LAST:event_b10ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        if(b9.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1tarola.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(2, true);
            System.out.println("Arreglo:" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        }else{
            sc.lin1.set(2,false);
            System.out.println("Arreglo:" + sc.lin1.toString());
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        if(b8.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4hi_hat.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(1, true);
            System.out.println("Arreglo:" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        }else{
            sc.lin4.set(1,false);
            System.out.println("Arreglo:" + sc.lin4.toString());
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        if(b7.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3bombo.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(1, true);
            System.out.println("Arreglo:" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        }else{
            sc.lin3.set(1,false);
            System.out.println("Arreglo:" + sc.lin3.toString());
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        if(b6.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2percusion.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(1, true);
            System.out.println("Arreglo:" + sc.lin2.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        }else{
            sc.lin2.set(1,false);
            System.out.println("Arreglo:" + sc.lin2.toString());
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        if(b5.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1tarola.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(1, true);
            System.out.println("Arreglo:" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        }else{
            sc.lin1.set(1,false);
            System.out.println("Arreglo:" + sc.lin1.toString());
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:

        if(b4.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("4hi_hat.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin4.set(0, true);
            System.out.println("Arreglo:" + sc.lin4.toString());
            clip4.open(audioStream);
        }catch(Exception e){

        }
        clip4.start();
        clip4.setFramePosition(0);
        }else{
            sc.lin4.set(0,false);
            System.out.println("Arreglo:" + sc.lin4.toString());
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        //sc.lin3.set(0) = true;
        if(b3.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("3bombo.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin3.set(0, true);
            System.out.println("Arreglo:" + sc.lin3.toString());
            clip3.open(audioStream);
        }catch(Exception e){

        }
        clip3.start();
        clip3.setFramePosition(0);
        }else{
            sc.lin3.set(0,false);
            System.out.println("Arreglo:" + sc.lin3.toString());
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        if(b2.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("2percusion.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin2.set(0, true);
            System.out.println("Arreglo:" + sc.lin1.toString());
            clip2.open(audioStream);
        }catch(Exception e){

        }
        clip2.start();
        clip2.setFramePosition(0);
        }else{
            sc.lin1.set(0,false);
            System.out.println("Arreglo:" + sc.lin1.toString());
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if(b1.isSelected()){
            try{
            URL soundURL = Consol.class.getResource("1tarola.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(soundURL);
            sc.lin1.set(0, true);
            System.out.println("Arreglo:" + sc.lin1.toString());
            clip1.open(audioStream);
        }catch(Exception e){

        }
        clip1.start();
        clip1.setFramePosition(0);
        }else{
            sc.lin1.set(0,false);
            System.out.println("Arreglo:" + sc.lin1.toString());
        }

    }//GEN-LAST:event_b1ActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        String texto = textRepeat.getText();
        if(texto.equals("loop")){
            sc.loop = true;
            sc.bpm = (int) 60000 / Integer.parseInt(textSpeed.getText());
        }else{
           sc.repeat = Integer.parseInt(texto);
           sc.loop = false;
           sc.bpm = (int) 60000/Integer.parseInt(textSpeed.getText());
        }
        System.out.println(texto);
        try{
            Socket paquete_enviar = new Socket("127.0.0.1",9999);//aquí se especifica la ip del servidor
            ObjectOutputStream paquete_salida = new ObjectOutputStream(paquete_enviar.getOutputStream());
            paquete_salida.writeObject(sc);
            paquete_enviar.close();

            
        }catch(Exception e){
            
        }

    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        try {
            // TODO add your handling code here:
            Socket paquete_enviar = new Socket("192.168.0.17",9998);
            ObjectOutputStream paquete_salida = new ObjectOutputStream(paquete_enviar.getOutputStream());
            paquete_salida.writeObject(new Detenerc());
            paquete_enviar.close();
        } catch (IOException ex) {
            Logger.getLogger(Consol.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStopActionPerformed

    private void textSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSpeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSpeedActionPerformed

    private void textRepeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRepeatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRepeatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws UnknownHostException, IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton b1;
    private javax.swing.JToggleButton b10;
    private javax.swing.JToggleButton b11;
    private javax.swing.JToggleButton b12;
    private javax.swing.JToggleButton b13;
    private javax.swing.JToggleButton b14;
    private javax.swing.JToggleButton b15;
    private javax.swing.JToggleButton b16;
    private javax.swing.JToggleButton b17;
    private javax.swing.JToggleButton b18;
    private javax.swing.JToggleButton b19;
    private javax.swing.JToggleButton b2;
    private javax.swing.JToggleButton b20;
    private javax.swing.JToggleButton b21;
    private javax.swing.JToggleButton b22;
    private javax.swing.JToggleButton b23;
    private javax.swing.JToggleButton b24;
    private javax.swing.JToggleButton b25;
    private javax.swing.JToggleButton b26;
    private javax.swing.JToggleButton b27;
    private javax.swing.JToggleButton b28;
    private javax.swing.JToggleButton b29;
    private javax.swing.JToggleButton b3;
    private javax.swing.JToggleButton b30;
    private javax.swing.JToggleButton b31;
    private javax.swing.JToggleButton b32;
    private javax.swing.JToggleButton b4;
    private javax.swing.JToggleButton b5;
    private javax.swing.JToggleButton b6;
    private javax.swing.JToggleButton b7;
    private javax.swing.JToggleButton b8;
    private javax.swing.JToggleButton b9;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField textRepeat;
    private javax.swing.JTextField textSpeed;
    // End of variables declaration//GEN-END:variables
}
